---
title: Beekeeping in, of, or for the city? A socioecological perspective on urban apiculture
author:
  - "Douglas B. Sponsler"
  - "Eve Z. Bratman"
output: 
  word_document:
    reference_docx: docx_template.docx
bibliography: refs.bib
---

**Abstract**


**Introduction**

*"Now bees," said Granny Weatherwax, "is real magic."* 
--- Terry Pratchett, *Equal Rites*

The most charismatic of mini-fauna, honey bees (Apis mellifera L.) have become a cause célèbre of environmentalism, thrust into the role of protagonist in contexts ranging from primary school curricula [@Cho2018-ul] to multinational litigation [e.g. @European_Food_Safety_Authority2013-li]. The legitimacy of the honey bee as a conservation proxy has been challenged [@Colla2017-fz; @Geldmann2018-ou], and debate about the attention the honey bee deserves relative to other species continues [@Kleijn2018-fh; @Saunders2018-yd]. Our concern here, though, is not with the ecological significance of honey bees as such, but rather with what may be considered an epiphenomenon of the honey bee’s prominence in the public imagination: the rise of urban beekeeping and its role in the socioecology of cities. 

While urban beekeeping occurs globally in various forms, our discussion will focus primarily on urban beekeeping in the United States. During the urban sanitation efforts of the 1920s [@Childers2014-au; @Grove2009-pv], restrictions on urban beekeeping became folded into ordinances prohibiting animal husbandry in cities, and zoning *for* animal agriculture in cities was almost inconceivable until the 1950s [@Brinkley2014-ey]. A renewed interest in urban "homesteading" took off in the early and mid-1970s, but urban beekeeping remained rare. Until the early 2000s, urban beekeeping and livestock ordinances tended to be restrictive rather than permissive, although there remained some variation both between different urban areas, and state or county laws sometimes take precedence over more prohibitive local zoning ordinances [@Meenar2012-si]. 

A significant rise in the number of hobbyist beekeepers --- including urban beekeepers --- began in the United States around 2008 [@Bee_Informed_Partnership2018-yz; @Usda-nass2018-yk], likely driven by the media attention garnered by reports of “colony collapse disorder” (CCD) that began in 2006 [@Vanengelsdorp2009-px]. CCD provided context, curiosity, and urgency, at the same time the public imagination was being sparked by best-selling books that helped to popularize the local food movement [@Pollan2006-mr; @Schlosser2012-cj]. By 2010, New York and Los Angeles lifted their restrictions on urban beekeeping, with Milwaukee, WI, and Washington DC following suit in 2012, creating an influential precedent for cities and municipalities across the country.

Today, urban beekeeping in the United States is an established practice, having outlived the initial media frenzy of the late-2000s that energized its rise from the status of an “underground” hobby, often in violation of city ordinances, to that of a celebrated urban amenity, often with explicit civic endorsement. Nevertheless, the real socioecological significance of urban beekeeping has yet to be analyzed rigorously. Our purpose in writing this perspective article is to begin the task of situating urban beekeeping explicitly within an urban socioecological framework wherein its significance can be analyzed and interpreted coherently. Using this framework, we explore the socioecological assets and liabilities of urban beekeeping, identify key modulators of these assets and liabilities, and conclude with a prospectus for the future of urban beekeeping and its place with the socioecology of the city.


**Extending urban ecological theory to urban beekeeping**

The history of urban ecology has been summarized in terms of three main paradigms: ecology *in*, *of*, and *for* the city [@Childers2014-au; @Pickett2016-gm]. The earliest of these, ecology *in* the city, conceives of “terrestrial and aquatic patches within cities, suburbs, and exurbs as analogs of non-urban habitats” [@Pickett2016-gm]. The central questions of ecology *in* the city concern the effect of the urban matrix (e.g. its built environment, impervious surfaces, density of human population, altered climate) on focal patches, and how these urban patches may differ from their non-urban counterparts. Building on the insights of ecology in the city, ecology *of* the city understands the city as a coupled human-natural system in which social and biogeophysical components are intertwined and mutually-constituted, operating in two-way relationships with complex feedback loops [@McPhearson2016-yd; @Pickett2016-gm]. Finally, ecology *for* the city takes on an explicitly transdisciplinary scope, aiming to apply ecological knowledge toward civic ends. In this approach, the aims and assumptions of urban ecology are nested within a broader ethic of sustainability, stewardship, and environmental justice [@Walker2004-lz], and knowledge is meant to inform action [Childers2014-au]. In keeping with these broader normative commitments, ecology *of* the city seeks genuine collaboration with urban stakeholders and policymakers, and ecologists doing research understand themselves to be embedded, self-critical members of society [@Pickett2016-gm]. The ecology *for* the city paradigm may be recognizable to most social scientists as having strong parallels to the field of political ecology.

We suggest that the *in*/*of*/*for* framework of urban ecological theory can be applied to the analysis of urban beekeeping. Our appropriation of this framework is intended as a heuristic strategy rather than a univocal use of the original formulation [@Childers2014-au; @Pickett2016-gm]. Nevertheless, insofar as urban beekeeping is an urban ecological phenomenon, an amalgam of natural processes with the human intricacies of the city, its relationship to urban ecological theory is far from merely nominal. 

*Beekeeping In the City.*   The key distinction of ecology *in* the city is that the urban landscape is seen as a context in which ecology occurs but not necessarily as an integrated ecological system. In the same sense, beekeeping *in* the city describes the practice of urban beekeeping that is only incidentally rather than constitutively urban. It occurs in the city but neither takes on a distinctly urban form integrated with the social and ecological context of the city, nor serves any explicit socioecological agenda beyond the relationship between bees and beekeeper. Beekeeping in the city should not, for these reasons, be dismissed as trivial, but the key trait of beekeeping *in* the city is the private scope of its understood significance: a unique, and at times profound, relationship between a person (the beekeeper) and a managed-yet-still-wild animal. The socioecological impacts, positive or negative, of such beekeeping are not null for being non-explicit, but they are *externalities*, in the economic sense of the word, with respect to the explicit exchange between bees and beekeeper.

*Beekeeping Of the City.*   Beekeeping *of* the city occurs when the practice of beekeeping is transformed by the exigencies of the urban context into a distinct trade, functionally integrated into the life of the city, yet not necessarily attached to any explicit socioecological agenda. This form of beekeeping is most apparent in (though not limited to) the subset of urban beekeepers (in most places, a small one) for whom beekeeping is a significant economic activity. The beekeeper is, by practical necessity, aware that beekeeping is contextualized by the ecology of city. The health and productivity of a honey bee colony hinges on the composition and dynamics of the local floral community, on regional weather and climate, and --- significantly --- on the decisions of neighboring beekeepers with respect to colony density and pest/pathogen management. Moreover, the beekeeper understands that the economic viability of beekeeping is intertwined with the economy of the city: the buying power of different human demographics, the trends in consumer interest in apicultural goods and services, the approach of consumers via marketing strategies. Beekeepers *of* the city become an expert community, a trade guild, with special knowledge of and interest in the socioecology of the city, at least insofar as it pertains to their beekeeping. The inverse of this relationship, however --- the impact of beekeeping on the socioecology of the city beyond the immediate exchanges between the beekeeping operation and the urban context --- remains an externality.

*Beekeeping For the City.*   Beekeeping can be said to be *for* the city when the socioecological impact of beekeeping, heretofore an externality, becomes an explicit objective. Beekeepers *for* the city understand their beekeeping as a form of environmental and social activism, of participation in the life of the city as such, a practice of ecological citizenship [@Light2003-xk]. Beekeeping for the city can be understood as a practice of re-imagining the place of nature in urban life-ways through the practice of inter-species relationships. This is, perhaps, the most conspicuous form of urban beekeeping in the public imagination because its practice is public by design, often accompanied by outspoken advocacy and invitation to participation. Its ethos is articulated well by geographer Jennifer Wolch: “we bring the bee into the urban landscape for intellectual, ecological, and moral reasons ‘to re-imagine the *anima Urbis*---the breath, life, soul, and spirit of the city---as embodied in its animal life” [@Wolch2002-te]. However, while emphasizing the normative agenda of beekeeping for the city, it is important to remember that socioecological zeal does not equal socioecological competency. In its most specious  (and, alas, not uncommon) forms, beekeeping for the city indulges in the fallacy that by merely stocking one's backyard with honey bee colonies, one will "save" bees, the city, or both [@Alton2016-iq]. We address this at greater length below.


**Socioecological Assets, Liabilities, and Normative Principles**

The three forms of urban beekeeping we suggest --- beekeeping *in*, *of*, and *for* the city --- are not mutually exclusive, nor do they form a straightforward gradient of socioecological value. Instead, they interact in complex ways with a suite of potential socioecological assets and liabilities, which we now discuss. 

*Pollination services.*   The majority of flowering plants are fully or partially dependent on animal pollinators for fruit and seed production [@Ollerton2011-du], and bees are by far the most important group of pollinators [@Willmer2017-lt]. While wild bees and other insect pollinators account for a substantial portion of the pollination often attributed to managed honey bees [@Garibaldi2013-tv], the honey bee has special value as a pollinator due to its global distribution and amenability to human management. The importance of the honey bee as a pollinator in urban landscapes, however, is virtually unstudied, and probably varies markedly across specific urban contexts. One cannot assume that the addition of honey bees to a landscape will improve pollination services to crops or wild plants without first establishing that (1) a deficit of pollination services exists and (2) honey bees serve as pollinators for the plants of concern [@Melathopoulos2015-yf]. Even where these conditions hold, the conventional monetary valuation of honey bee pollination services would be of uncertain relevance in urban systems where pollination is not as consistently linked to the sale of produce. Nevertheless, it is likely that many plants in urban localities benefit from honey bee pollination, and this service, though poorly studied and difficult to quantify, is rightly recognized as a legitimate asset of urban beekeeping. Where beekeeping can be strategically integrated into the production of pollinator-dependent crops in urban agricultural systems, it has the potential to become uniquely *of* and *for* the city, functioning as part of an interconnected social, ecological, and technological system (SETS), a stewarded interconnection between social and natural worlds [@Markolf2018-ml; @Cousins2018-oi]. 

*Resource competition.*   The mutualism between plants and pollinators is often viewed as a sort of ecological sacrament; yet it is also a material exchange of finite resources. Plants share a finite pool of pollinator visitation while pollinators share a finite pool of floral nectar and pollen, and sharing becomes competition when either resource is limiting. There is growing empirical evidence that, at sufficient density, honey bees competitively limit local wild bees [e.g. @Henry2018-yz]. The generality and serverity of this phenomenon in urban areas remains uncertain [@McCune2019-nn; @Ropars2019-vw], but it is important to note that competition need not be constant or even frequent to be influential, since one lean year in ten might be sufficient to drive local extinctions that would persist unless reversed by immigration [@MacArthur1984-qz]. Honey bee colonies also compete with one another [@Henry2018-yz], and this has, anecdotally, become a problem for beekeepers in cities such as London and New York, where the popularity of urban beekeeping has led to dramatic increases in colony density [@Nessen2012-lk; @Alton2016-iq]. 

*Disease transmission to other insects.*   Honey bees are afflicted by a host of viral, bacterial, and fungal pathogens [@Evans2011-hl]. Traditionally, these maladies have tended to be characterized as “honey bee diseases”, but recent research has revealed that many of these pathogens can infect other insect species and that managed honey bees might serve as a reservoir and vector of disease for wild bees [@Graystock2016-zz]. The significance of this effect remains poorly understood [@Mallinger2017-at], but it is likely that the risk of disease transmission between honey bees and wild bees depends largely on honey bee colony density, raising concerns that increasing colony density in cities driven by the popularity of urban beekeeping [@Alton2014-py] may compromise the potential of urban habitats for wild bee conservation [@Hall2017-it]. Moreover, whatever uncertainty may remain with respect to the transmission of disease between honey bees and non-Apis bees, there is no doubt that honey bees transmit pathogens to each other[e.g. @Peck2019-om], this can be a cause of strife among neighboring beekeepers. 

*Stinging.*   Bans on urban beekeeping are typically motivated by concerns for public safety [@Moore2013-zw]. Honey bee venom has evolved to cause pain, not injury, in vertebrates [@Schmidt2014-eh], but for approximately 0.15-0.8% of children and 0.5-7.5% of adults, insect stings can induce systemic allergic reactions that are potentially life-threatening [@Bilo2008-if]. Thus, minimizing the risk of stings needs to be a top priority when keeping bees in densely populated areas. This may be achieved through signage, fencing, strategic hive placement, and careful colony management [@Garbuzov2014-jm; @Melathopoulos2018-yn]. Honey bees ordinarily sting only in the immediate vicinity of their hive, usually in response to some form of disturbance. Nevertheless, the risk of bystanders being stung needs to be taken very seriously when evaluating the propriety of beekeeping in any particular urban context. 

For beekeepers themselves, however, stings are routine and should not be regarded as problematic. Indeed, getting stung is considered by most beekeepers to be a constituive part of the beekeeping experience: a reminder, perhaps, that the relationship between a beekeeper and a honey bee colony is one of a human and a wild animal, not of an owner and a pet. It “forces you to take a deep breath, and be present” said one leader of a workshop on the social impact of bees at the World Beekeeping Congress in the fall of 2019. Philadelphia beekeeper Kirk Wattles described the experience of getting stung in even more overtly metaphysical terms:

>“I think it's definitely part of the social dimension of beekeeping — what we tell ourselves, and what we tell others, etc. With all the 'telling', though, I realized at one point that a bee sting is also a brush with reality, piercing the veil, not just words and stories, and for me that gives it an interesting philosophical dimension. The randomness also is a factor.”

*Apicultural products and livelihoods*   While there are no reliable data on the gross economic significance of urban beekeeping, urban beekeepers market their trade in a variety of ways. These include the sale of hive products (e.g. honey, wax, pollen, propolis) and their derivatives, the contracted management of hives on behalf of individuals or businesses, and the capture and removal of unwanted swarms or feral colonies. For most, these economic outlets are minor sources of income, but there are some cases of urban beekeepers for whom apiculture is a true livelihood, and sometimes even a source of employment for others. At a corporate level, the Boston-based Best Bees Company offers contracted beekeeping services in several metropolitan areas across the United States, with employees in all those locations. Many similar businesses operate at a local scale, such as the Philadelphia Bee Company, the Chicago Honey Co-Op, or the Bay Area Bee Company. 

A distinct but related consideration of urban socio-ecological value concerns the significance of hive products as a unique reflection of the neighborhoods from which they come. Localization of food consumption and alternative food practices, such as shopping at farmer’s markets, are often heralded as practices that foster community cohesion through the communal and relational experiences they offer. A sense of local pride in community-based relationships, a lighter environmental footprint, and a resistance to the distancing of the global food system may accompany such measures and be wrapped up in the symbolism of buying and eating locally. A word of caution is also merited, however; like community gardening and the creation of new parks, beekeeping and the consumption of micro-local honeys that fetch very high market prices may involve both a symbol and practice of “sustainability lifestyles” that tend to accompany green gentrification [@Checker2011-zi; @Gould2016-vz]. Unwittingly, such practices and consumption choices may entrench rather than mitigate the racialized and economically unequal dynamics of urban spaces and social relations. 

*Expert community formation.*   To the extent that beekeeping is undertaken seriously, the beekeeper becomes an entomologist, a botanist, an ecologist, and --- almost inevitably --- an environmental educator. At the most obvious level, a beekeeper learns the biology of honey bees. A competent beekeeper, though, also knows the local floral community and its seasonal phenology well enough to plan colony management around the timing of nectar flows (periods of high honey production) and dearths, possibly with the goal of producing high-value varietal honeys from known floral sources. Such knowledge amounts to an ecological understanding of the relationships between bees, plants, and the abiotic conditions that contextualize them in a given locality: a form of expertise that, especially in predominantly (though not completely) “post-agrarian” milieu of urban society, is virtually endemic to the urban beekeeping community. Unique opportunities thus arise for beekeepers to engage ecological issues beyond the immediate scope of their beekeeping [@Maderson2016-jf]. A beekeeper from Ontario who runs a business setting up honeybee hives on others’ private land articulated this quite clearly: 

>We make beekeeping a possibility for private landowners who have no desire to be a beekeeper, but they're well aware of the issues facing this planet, the bees, the land, etc. [...] So while we started out with [...] honeybees being the main sort of service that we offer our clients, we find ourselves more and more in a position of being advisors [...]. So our business has taken a very interesting direction in the sense that we do advise on how you can convert, say, a [...] farmer who spraying his or her crops. It's a critical story about bringing land back to sort of its natural state, about the importance of hedge rows, the importance of native pollinators (Apimondia 2019 session on “Social Impact of Bees”, Montreal, Canada).

In our firsthand experience of working with urban beekeepers in Philadelphia, we can attest that one can scarcely make it through a day of urban beekeeping without becoming engaged in conversations with interested bystanders, and these conversations frequently extend well beyond the beekeeping at hand to broader topics of plants, pollinators, and urban ecology. 

When the expertise catalyzed by beekeeping spreads beyond the individual beekeeper through the sharing of knowledge and experience with the larger community, beekeeping becomes a source of ecological literacy [@Orr1990-sj] and potentially ecological citizenship [@Light2003-xk], with honey bees serving as mediators between people and place. We summarize this with the term “ecological *rapprochement*” to capture the sense of restoring immediacy between people and nature amid the artifice of urban landscapes [sensu @Kohak1984-tf]. Ecological *rapprochement* is fostered when beekeeping is both *of* and *for* the city. The former is necessary for the cultivation of local ecological expertise through beekeeping that appreciates the city as its ecological context. The latter is necessary for its impetus to engage the public in the learning process.

Illustrative of this concept is the story of Sarah Common, who co-foundeed Vancouver’s non-profit organization Hives for Humanity with her mother, Julia Common, a long-time beekeeper. Sarah described how she got into this work and its broader significance:

>I was in foods and in community, and people were asking how we can get more involved in our food, so they came to a garden. And then in that garden, people were asking how we can bring more people into the garden and how we can create more connection in that garden. And then, that coincided with the conversation I had with my mother, who's been beekeeping for 40 plus years. [...] So you know, connecting to myself and to some of my agency and to my connection to nature and who I am; that really has been through the bees for me and in my life, like from 26 to 34 now, and connecting to my mom through that and understanding, you know, who we are together and who she is beyond provider and parent. And also connecting to my city and understanding what the land we're on there, and who the people who were there before and what the waters mean, and what the forest means has all been through the bees for me. And that's really what I continue to try and support through these is connection to community to nature unto itself.”

It is also worth noting that at times, an urban beekeeper may drop out of beekeeping, but bees may be an entry point into broader ecological stewardship. As another beekeeper observed: 

> backyard beekeepers are finding their way back to native pollinators and native plants, and really a more sustainable way to garden. [...] It seems like through honey bees, I certainly see transformations in what people are doing. I mean, I see more native plants in beekeepers' gardens, and I see them trying to support native pollinators, even to the extent that it's really hard for backyard beekeepers, who eventually will give up honey bees, but continue supporting native populations, which is really encouraging.


**Guidelines for maturing urban beekeeping**

The discussion above leads us to suggest several guidelines for maximizing the socioecological assets and minimizing the socioecological liabilities of urban beekeeping. Technical best practices for urban beekeeping have been discussed comprehensively elsewhere [@Melathopoulos2018-yn]. Instead, we focus more generally on attitudes and collective strategies, the goal of which is to foster the maturation of urban beekeeping from an experimental cultural movement to a self-critical, organized, purposeful, and beneficent form of ecological citizenship.

*Limit colony density*.   A key observation that emerges from our analysis is that the liabilities of urban beekeeping, more so than its assets, are tightly linked to colony density. It has been suggested that, at a regional scale, apiary spacing rather than colony density should be the object of regulation, since this approach could maintain low-competition zones in the interstices of the foraging radii of neighboring apiaries while allowing individual apiaries to operate at a commercially viable scale [@Henry2020-rb]. This approach is probably ill-suited for urban environments, though, because the spacing required to leave appreciable competition gaps between neighboring apiaries (>2 km) [@Henry2020-rb] would either exclude the majority of beekeepers or force a degree of spatial consolidation that would result in impractically large urban apiaries. Moreover, for most urban beekeepers, the question of apiary location is a moot point, since their own rooftops or backyards are the only spaces they have at their disposal. 

Colony density as an object of top-down regulation, however, poses a serious policy conundrum, since it is a phenomenon that, akin to the issue of non-point-source pollution, emerges as the cumulative product of many individual decisions. Insofar as honey bee colonies are treated as semi-regulated private property, there is little a municipal government can do to limit colony density aside from limiting the number of colonies that can be kept on a given parcel of land. Since urban land parcels are small and densely packed, the link between parcel-level apiary and landscape-level colony density should be regarded as tenuous. 

While affirming a role for civic ordinances, we suggest that both the onus and the capacity --- and, indeed, the awareness and motivation --- for regulating colony density are to be found primarily within the beekeeping community itself. Drawing on the *in*/*of*/*for* framework, a basis for self-regulation might be found in a marriage of the "trade guild" qualities of beekeeping *of* the city with the civic consciousness of beekeeping *for* the city. Indeed, the word "guild", with its rich (though checkered) history of organizing and regulating, is a , has been adopted explicitly by some urban beekeeping groups, including the Philadelphia Beekeepers Guild. 
> For me, these discussions are in the framework of the word 'Guild.' We're not simply a 'club' or an 'association' [...]. Guilds set the standards, and historically they also tried to control entry into the trade, in order to reduce numbers and boost prices. The [Philadelphia Beekeepers Guild] doesn't really try to do that, and we couldn't if we wanted to, but I think there are ways we can model good practices and help people understand the responsibilities. (Kirk Wattles, Philadelphia Beekeepers Guild member)

a well-integrated social fabric, in which one’s decision to become a beekeeper and one’s beekeeping practices  occur in a context both of support and accountability

Analogous to the self-regulation of pesticide use by the California almond growers conscious of their dependence on honey bee pollination [@Sponsler2019-pn]. 



*Foster beekeeper training*

*Prioritize ecological rapprochement*.   Urban beekeeping places insect life and animal husbandry into the heart of cities that have long histories of being ‘sanitary’ spaces, urban beekeeping begins by promoting a greater sense of inter-species relationship, and even, perhaps, a sense of interspecies kinship. 

*Make explicit the political ecology of urban beekeeping*.   The relationships of beekeeping to other urban food justice efforts, likewise, is an arena for further research. A scholarly lacuna presently exists on the topic of how beekeeping’s economic and social value is distributed across different racial, ethnic, and class lines. Analysis of the effects policy coordination and municipal regulations may play in generating socioecologically desirable outcomes is another important area for further research and analysis. While existing research has focused on the question of food insecurity, pesticides, and anti-neoliberal perspectives in food justice [@Ellis2019-tj], scholarship has yet to treat the question of how beekeeping may further environmental justice goals, and how ecological justice may inform a more integrative approach to beekeeping.


**Conclusion**

Importantly, our analysis has focused on urban beekeeping in the United States. While some of our points may generalize to other contexts, others will not. For example, the economic significance of urban beekeeping depends on the larger economic system in which it occurs. In the U.S., small-scale beekeepers are most often hobbyists who make little or no profit from their hives, while small-scale beekeeping in Zambia is a significant and growing economic sector [@Mickels-Kokwe2006-bd]. Little is known about how the economic significance of urban beekeeping varies geographically. 


**Acknowledgements**
We thank D. Shump for invaluable conversation and for generous access to his urban beekeeping operation, and members of the Environments reading group at Franklin & Marshall College for their feedback on an early version of this paper.

**Author contributions**
Both authors conceived the project and wrote the paper. E. Bratman carried out the ethnographic field work.


**References**







